<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'name' => 'light deal product 1',
                'slug' => Str::slug('light deal product 1'),
                'thumbnail' => 'frontend/images/light-deal-1.png',
                'short_description' => 'light deal product-1',
                'description' => 'light deal product-1',
                'buying_price' => 700.00,
                'selling_price' => 25.00,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 50,
                'category_id' => 1,
                'brand_id' => 1,
                'shop_id' => 1,
                'sku' => 'SGS21-001',
                'barcode' => '1234567890123',
                'is_trending' => 0,
                'best_selling' => 0,
                'is_featured' => 0,
                'is_lightdeal' => 1,
                'lightdeal_expired_at'=> now()->addHours(7),
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 50,
                'stock_out' => 4500,
                'shipping_cost' => 5.00,
                'tax' => 12.00,
                'views' => 2000,
                'meta_title' => 'light deal product 1',
                'meta_keywords' => 'light deal product 1',
                'meta_desc' => 'light deal product 1',
            ],
            [
                'name' => 'light deal product 2',
                'slug' => Str::slug('light deal product 2'),
                'thumbnail' => 'frontend/images/light-deal-2.png',
                'short_description' => 'light deal product 2',
                'description' => 'light deal product 2',
                'buying_price' => 800.00,
                'selling_price' => 40.00,
                'discount_type' => 'fixed',
                'discount_amount' => 50.00,
                'quantity' => 30,
                'category_id' => 1,
                'brand_id' => 2,
                'shop_id' => 1,
                'sku' => 'IP13-001',
                'barcode' => '9876543210987',
                'is_trending' => 0,
                'best_selling' => 0,
                'is_featured' => 0,
                'is_lightdeal' => 1,
                'lightdeal_expired_at' => now()->addHours(8),
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 30,
                'stock_out' => 8200,
                'shipping_cost' => 5.00,
                'tax' => 12.00,
                'views' => 1500,
                'meta_title' => 'light deal product 2',
                'meta_keywords' => 'iPhone, Apple, Smartphone, Electronics',
                'meta_desc' => 'light deal product 2',
            ],
            [
                'name' => 'light deal product 3',
                'slug' => Str::slug('light deal product 3'),
                'thumbnail' => 'frontend/images/light-deal-3.png',
                'short_description' => 'light deal product 3',
                'description' => 'light deal product 3',
                'buying_price' => 250.00,
                'selling_price' => 30.00,
                'discount_type' => 'percentage',
                'discount_amount' => 15.00,
                'quantity' => 20,
                'category_id' => 1,
                'brand_id' => 3,
                'shop_id' => 1,
                'sku' => 'WH1000XM4-001',
                'barcode' => '1112223334445',
                'is_trending' => 0,
                'best_selling' => 0,
                'is_featured' => 0,
                'is_lightdeal' => 1,
                'lightdeal_expired_at' => now()->addHours(1),
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 20,
                'stock_out' => 1900,
                'shipping_cost' => 5.00,
                'tax' => 8.00,
                'views' => 1000,
                'meta_title' => 'light deal product 3',
                'meta_keywords' => 'Sony, Headphones, Noise-canceling, Electronics',
                'meta_desc' => 'light deal product 3',
            ],
            [
                'name' => 'light deal product 4',
                'slug' => Str::slug('light deal product 4'),
                'thumbnail' => 'frontend/images/light-deal-4.png',
                'short_description' => 'light deal product 4',
                'description' => 'light deal product 4',
                'buying_price' => 90.00,
                'selling_price' => 99.99,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 40,
                'category_id' => 2,
                'brand_id' => 4,
                'shop_id' => 2,
                'sku' => 'AM90-001',
                'barcode' => '7778889990001',
                'is_trending' => 0,
                'best_selling' => 0,
                'is_featured' => 0,
                'is_lightdeal' => 1,
                'lightdeal_expired_at' => now()->addHours(2),
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 40,
                'stock_out' => 500,
                'shipping_cost' => 7.00,
                'tax' => 10.00,
                'views' => 900,
                'meta_title' => 'light deal product 4',
                'meta_keywords' => 'Nike, Air Max 90, Shoes, Fashion',
                'meta_desc' => 'light deal product 4',
            ],
            [
                'name' => 'light deal product 5',
                'slug' => Str::slug('light deal product 5'),
                'thumbnail' => 'frontend/images/light-deal-5.png',
                'short_description' => 'light deal product 5',
                'description' => 'Tlight deal product 5',
                'buying_price' => 120.00,
                'selling_price' => 299.99,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 35,
                'category_id' => 2,
                'brand_id' => 5,
                'shop_id' => 2,
                'sku' => 'UB21-001',
                'barcode' => '1122334455667',
                'is_trending' => 0,
                'best_selling' => 0,
                'is_featured' => 0,
                'is_lightdeal' => 1,
                'lightdeal_expired_at' => now()->addHours(4),
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 35,
                'stock_out' => 10500,
                'shipping_cost' => 7.00,
                'tax' => 12.00,
                'views' => 800,
                'meta_title' => 'light deal product 5',
                'meta_keywords' => 'Adidas, Ultraboost 21, Sneakers, Fashion',
                'meta_desc' => 'light deal product 5',
            ],
        ];

        foreach ($products as $product) {
            DB::table('products')->insert([
                'name' => $product['name'],
                'slug' => $product['slug'],
                'thumbnail' => $product['thumbnail'],
                'short_description' => $product['short_description'],
                'description' => $product['description'],
                'buying_price' => $product['buying_price'],
                'selling_price' => $product['selling_price'],
                'discount_type' => $product['discount_type'],
                'discount_amount' => $product['discount_amount'],
                'quantity' => $product['quantity'],
                'category_id' => $product['category_id'],
                'brand_id' => $product['brand_id'],
                'shop_id' => $product['shop_id'],
                'sku' => $product['sku'],
                'barcode' => $product['barcode'],
                'is_trending' => $product['is_trending'],
                'is_lightdeal' => $product['is_lightdeal'],
                'lightdeal_expired_at' => $product['lightdeal_expired_at'],
                'best_selling' => $product['best_selling'],
                'is_featured' => $product['is_featured'],
                'status' => $product['status'],
                'stock_status' => $product['stock_status'],
                'stock_in' => $product['stock_in'],
                'stock_out' => $product['stock_out'],
                'shipping_cost' => $product['shipping_cost'],
                'tax' => $product['tax'],
                'views' => $product['views'],
                'meta_title' => $product['meta_title'],
                'meta_keywords' => $product['meta_keywords'],
                'meta_desc' => $product['meta_desc'],
            ]);
        }
    }
}
