<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            //light deal
            [
                'name' => 'light deal product 1',
                'slug' => Str::slug('light deal product 1'),
                'thumbnail' => 'images/products/light-deal-1.png',
                'short_description' => 'light deal product-1',
                'description' => 'light deal product-1',
                'buying_price' => 700.00,
                'selling_price' => 25.00,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 50,
                'category_id' => 1,
                'brand_id' => 1,
                'seller_id' => 1,
                'sku' => 'SGS21-001',
                'barcode' => '1234567890123',
                'is_lightdeal' => 1,
                'lightdeal_expired_at' => now()->addHours(7),
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 50,
                'stock_out' => 4500,
                'shipping_cost' => 5.00,
                'tax' => 12.00,
                'views' => 2000,
                'meta_title' => 'light deal product 1',
                'meta_keywords' => 'light deal product 1',
                'meta_desc' => 'light deal product 1',
            ],
            [
                'name' => 'light deal product 2',
                'slug' => Str::slug('light deal product 2'),
                'thumbnail' => 'images/products/light-deal-2.png',
                'short_description' => 'light deal product 2',
                'description' => 'light deal product 2',
                'buying_price' => 800.00,
                'selling_price' => 40.00,
                'discount_type' => 'fixed',
                'discount_amount' => 50.00,
                'quantity' => 30,
                'category_id' => 1,
                'brand_id' => 2,
                'seller_id' => 1,
                'sku' => 'IP13-001',
                'barcode' => '9876543210987',
                'is_lightdeal' => 1,
                'lightdeal_expired_at' => now()->addHours(8),
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 30,
                'stock_out' => 8200,
                'shipping_cost' => 5.00,
                'tax' => 12.00,
                'views' => 1500,
                'meta_title' => 'light deal product 2',
                'meta_keywords' => 'iPhone, Apple, Smartphone, Electronics',
                'meta_desc' => 'light deal product 2',
            ],
            [
                'name' => 'light deal product 3',
                'slug' => Str::slug('light deal product 3'),
                'thumbnail' => 'images/products/light-deal-3.png',
                'short_description' => 'light deal product 3',
                'description' => 'light deal product 3',
                'buying_price' => 250.00,
                'selling_price' => 30.00,
                'discount_type' => 'percentage',
                'discount_amount' => 15.00,
                'quantity' => 20,
                'category_id' => 1,
                'brand_id' => 3,
                'seller_id' => 1,
                'sku' => 'WH1000XM4-001',
                'barcode' => '1112223334445',
                'is_lightdeal' => 1,
                'lightdeal_expired_at' => now()->addHours(1),
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 20,
                'stock_out' => 1900,
                'shipping_cost' => 5.00,
                'tax' => 8.00,
                'views' => 1000,
                'meta_title' => 'light deal product 3',
                'meta_keywords' => 'Sony, Headphones, Noise-canceling, Electronics',
                'meta_desc' => 'light deal product 3',
            ],
            [
                'name' => 'light deal product 4',
                'slug' => Str::slug('light deal product 4'),
                'thumbnail' => 'images/products/light-deal-4.png',
                'short_description' => 'light deal product 4',
                'description' => 'light deal product 4',
                'buying_price' => 90.00,
                'selling_price' => 99.99,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 40,
                'category_id' => 2,
                'brand_id' => 4,
                'seller_id' => 1,
                'sku' => 'AM90-001',
                'barcode' => '7778889990001',
                'is_lightdeal' => 1,
                'lightdeal_expired_at' => now()->addHours(2),
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 40,
                'stock_out' => 500,
                'shipping_cost' => 7.00,
                'tax' => 10.00,
                'views' => 900,
                'meta_title' => 'light deal product 4',
                'meta_keywords' => 'Nike, Air Max 90, Shoes, Fashion',
                'meta_desc' => 'light deal product 4',
            ],
            [
                'name' => 'light deal product 5',
                'slug' => Str::slug('light deal product 5'),
                'thumbnail' => 'images/products/light-deal-5.png',
                'short_description' => 'light deal product 5',
                'description' => 'Tlight deal product 5',
                'buying_price' => 120.00,
                'selling_price' => 299.99,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 35,
                'category_id' => 2,
                'brand_id' => 5,
                'seller_id' => 1,
                'sku' => 'UB21-001',
                'barcode' => '1122334455667',
                'is_trending' => 0,
                'best_selling' => 0,
                'is_featured' => 0,
                'is_lightdeal' => 1,
                'lightdeal_expired_at' => now()->addHours(4),
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 35,
                'stock_out' => 10500,
                'shipping_cost' => 7.00,
                'tax' => 12.00,
                'views' => 800,
                'meta_title' => 'light deal product 5',
                'meta_keywords' => 'Adidas, Ultraboost 21, Sneakers, Fashion',
                'meta_desc' => 'light deal product 5',
            ],

            // interest products
            [
                'name' => 'Muffets & Tuffets Whole Wheat Bread 400 g',
                'slug' => Str::slug('Muffets & Tuffets Whole Wheat Bread 400 g'),
                'thumbnail' => 'images/products/int-pro-1.png',
                'short_description' => 'light deal product 5',
                'description' => 'Tlight deal product 5',
                'buying_price' => 120.00,
                'selling_price' => 80.99,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 35,
                'unit' => '1 KG',
                'category_id' => 2,
                'brand_id' => 5,
                'seller_id' => 1,
                'sku' => 'INT21-001',
                'barcode' => '1122334455671',
                'is_interest' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 35,
                'stock_out' => 10500,
                'shipping_cost' => 7.00,
                'tax' => 12.00,
                'views' => 800,
            ],
            [
                'name' => 'Tracker for Android IPhone Devices',
                'slug' => Str::slug('Tracker for Android IPhone Devices'),
                'thumbnail' => 'images/products/int-pro-2.png',
                'short_description' => 'light deal product 5',
                'description' => 'Tlight deal product 5',
                'buying_price' => 120.00,
                'selling_price' => 120.00,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 35,
                'unit' => '1 piece',
                'category_id' => 2,
                'brand_id' => 5,
                'seller_id' => 1,
                'sku' => 'INT21-002',
                'barcode' => '1122334455672',
                'is_interest' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 35,
                'stock_out' => 10500,
                'shipping_cost' => 7.00,
                'tax' => 12.00,
                'views' => 800,
            ],
            [
                'name' => 'Exclusive T-Shirt, Shirt, & Gavadin Pant Combo',
                'slug' => Str::slug('Exclusive T-Shirt, Shirt, & Gavadin Pant Combo'),
                'thumbnail' => 'images/products/int-pro-3.png',
                'short_description' => 'light deal product 5',
                'description' => 'Tlight deal product 5',
                'buying_price' => 120.00,
                'selling_price' => 299.00,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 35,
                'unit' => '3 piece',
                'category_id' => 2,
                'brand_id' => 5,
                'seller_id' => 1,
                'sku' => 'INT21-003',
                'barcode' => '1122334455673',
                'is_interest' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 35,
                'stock_out' => 10500,
                'shipping_cost' => 7.00,
                'tax' => 12.00,
                'views' => 800,
            ],
            [
                'name' => 'Imported Sheep\'s wool Shoe for Winter',
                'slug' => Str::slug('Imported Sheep\'s wool Shoe for Winter'),
                'thumbnail' => 'images/products/int-pro-4.png',
                'short_description' => 'light deal product 5',
                'description' => 'Tlight deal product 5',
                'buying_price' => 120.00,
                'selling_price' => 99.00,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 35,
                'unit' => '1 pair',
                'category_id' => 2,
                'brand_id' => 5,
                'seller_id' => 1,
                'sku' => 'INT21-004',
                'barcode' => '1122334455674',
                'is_interest' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 35,
                'stock_out' => 10500,
                'shipping_cost' => 7.00,
                'tax' => 12.00,
                'views' => 800,

            ],
            [
                'name' => 'Men\'s Solid Slim Width Necktie',
                'slug' => Str::slug('Men\'s Solid Slim Width Necktie'),
                'thumbnail' => 'images/products/int-pro-5.png',
                'short_description' => 'light deal product 5',
                'description' => 'Tlight deal product 5',
                'buying_price' => 120.00,
                'selling_price' => 99.99,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 35,
                'unit' => '1 pair',
                'category_id' => 2,
                'brand_id' => 5,
                'seller_id' => 1,
                'sku' => 'INT21-005',
                'barcode' => '1122334455675',
                'is_interest' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 35,
                'stock_out' => 10500,
                'shipping_cost' => 7.00,
                'tax' => 12.00,
                'views' => 800,
            ],
            [
                'name' => 'Exclusive T-Shirt & Gavadin Pant Combo',
                'slug' => Str::slug('Exclusive T-Shirt & Gavadin Pant Combo'),
                'thumbnail' => 'images/products/int-pro-3.png',
                'short_description' => 'light deal product 5',
                'description' => 'Tlight deal product 5',
                'buying_price' => 120.00,
                'selling_price' => 299.00,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 35,
                'unit' => '3 piece',
                'category_id' => 2,
                'brand_id' => 5,
                'seller_id' => 1,
                'sku' => 'INT21-006',
                'barcode' => '1122334455676',
                'is_interest' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 35,
                'stock_out' => 10500,
                'shipping_cost' => 7.00,
                'tax' => 12.00,
                'views' => 800,
            ],

            //trending product
            [
                'name' => 'Meatigo Premium Goat Curry',
                'slug' => Str::slug('Meatigo Premium Goat Curry'),
                'thumbnail' => 'images/products/trend-prod-1.png',
                'short_description' => 'light deal product 5',
                'description' => 'Tlight deal product 5',
                'buying_price' => 120.00,
                'selling_price' => 70.00,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 35,
                'unit' => '450 G',
                'category_id' => 2,
                'brand_id' => 5,
                'seller_id' => 1,
                'sku' => 'TND21-001',
                'barcode' => '1122334455677',
                'is_trending' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 35,
                'stock_out' => 10500,
                'shipping_cost' => 7.00,
                'tax' => 12.00,
                'views' => 800,
            ],
            [
                'name' => 'Coral Bean Bag Chair',
                'slug' => Str::slug('Coral Bean Bag Chair'),
                'thumbnail' => 'images/products/trend-prod-2.png',
                'short_description' => 'light deal product 5',
                'description' => 'Tlight deal product 5',
                'buying_price' => 120.00,
                'selling_price' => 40.00,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 35,
                'unit' => '450 G',
                'category_id' => 2,
                'brand_id' => 5,
                'seller_id' => 1,
                'sku' => 'TND21-007',
                'barcode' => '1122334455678',
                'is_trending' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 35,
                'stock_out' => 10500,
                'shipping_cost' => 7.00,
                'tax' => 12.00,
                'views' => 800,
            ],
            [
                'name' => 'Benefits of using natural ston adash asb',
                'slug' => Str::slug('Benefits of using natural ston adash asb'),
                'thumbnail' => 'images/products/trend-prod-3.png',
                'short_description' => 'light deal product 5',
                'description' => 'Tlight deal product 5',
                'buying_price' => 120.00,
                'selling_price' => 80.00,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 35,
                'unit' => '1 KG',
                'category_id' => 2,
                'brand_id' => 5,
                'seller_id' => 1,
                'sku' => 'TND21-008',
                'barcode' => '1122334455679',
                'is_trending' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 35,
                'stock_out' => 10500,
                'shipping_cost' => 7.00,
                'tax' => 12.00,
                'views' => 800,
            ],

            //community products
            [
                'name' => 'Fresh Organic Potatoes',
                'slug' => Str::slug('Fresh Organic Potatoes'),
                'thumbnail' => 'images/products/community-pro-1.png',
                'short_description' => 'High-quality organic potatoes.',
                'description' => 'Freshly harvested organic potatoes, perfect for cooking.',
                'buying_price' => 30.00,
                'selling_price' => 40.00,
                'discount_type' => 'percentage',
                'discount_amount' => 5.00,
                'quantity' => 100,
                'unit' => '1 KG',
                'category_id' => 6,
                'brand_id' => 2,
                'seller_id' => 1,
                'sku' => 'GRY-POT-001',
                'barcode' => '1234567890123',
                'is_community' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 100,
                'stock_out' => 50,
                'shipping_cost' => 5.00,
                'tax' => 2.00,
                'views' => 500,
            ],
            [
                'name' => 'Premium Basmati Rice',
                'slug' => Str::slug('Premium Basmati Rice'),
                'thumbnail' => 'images/products/community-pro-2.png',
                'short_description' => 'Finest quality Basmati rice.',
                'description' => 'Long-grain aromatic Basmati rice, best for biryani and pulao.',
                'buying_price' => 80.00,
                'selling_price' => 100.00,
                'discount_type' => 'flat',
                'discount_amount' => 10.00,
                'quantity' => 200,
                'unit' => '5 KG',
                'category_id' => 6,
                'brand_id' => 3,
                'seller_id' => 1,
                'sku' => 'GRY-RICE-002',
                'barcode' => '2345678901234',
                'is_community' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 200,
                'stock_out' => 30,
                'shipping_cost' => 10.00,
                'tax' => 5.00,
                'views' => 300,
            ],
            [
                'name' => 'Farm Fresh Eggs',
                'slug' => Str::slug('Farm Fresh Eggs'),
                'thumbnail' => 'images/products/community-pro-3.png',
                'short_description' => '12 pieces of fresh farm eggs.',
                'description' => '100% organic and farm-fresh eggs rich in protein.',
                'buying_price' => 60.00,
                'selling_price' => 75.00,
                'discount_type' => 'percentage',
                'discount_amount' => 5.00,
                'quantity' => 50,
                'unit' => '1 Dozen',
                'category_id' => 6,
                'brand_id' => 4,
                'seller_id' => 1,
                'sku' => 'GRY-EGG-003',
                'barcode' => '3456789012345',
                'is_community' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 50,
                'stock_out' => 20,
                'shipping_cost' => 5.00,
                'tax' => 3.00,
                'views' => 700,
            ],
            [
                'name' => 'Almonds (Premium Quality)',
                'slug' => Str::slug('Almonds Premium Quality'),
                'thumbnail' => 'images/products/community-pro-4.png',
                'short_description' => 'Rich in nutrients and taste.',
                'description' => 'Handpicked, organic almonds for a healthy lifestyle.',
                'buying_price' => 250.00,
                'selling_price' => 300.00,
                'discount_type' => 'flat',
                'discount_amount' => 20.00,
                'quantity' => 80,
                'unit' => '500 gm',
                'category_id' => 6,
                'brand_id' => 5,
                'seller_id' => 1,
                'sku' => 'GRY-ALM-004',
                'barcode' => '4567890123456',
                'is_community' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 80,
                'stock_out' => 10,
                'shipping_cost' => 12.00,
                'tax' => 8.00,
                'views' => 600,
            ],
            [
                'name' => 'Pure Cow Ghee',
                'slug' => Str::slug('Pure Cow Ghee'),
                'thumbnail' => 'images/products/community-pro-2.png',
                'short_description' => '100% pure and organic cow ghee.',
                'description' => 'Traditional desi cow ghee, made from fresh cream.',
                'buying_price' => 400.00,
                'selling_price' => 450.00,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 30,
                'unit' => '1 Litre',
                'category_id' => 6,
                'brand_id' => 6,
                'seller_id' => 1,
                'sku' => 'GRY-GHEE-005',
                'barcode' => '5678901234567',
                'is_community' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 30,
                'stock_out' => 5,
                'shipping_cost' => 15.00,
                'tax' => 10.00,
                'views' => 900,
            ],
            [
                'name' => 'Raw Honey',
                'slug' => Str::slug('Raw Honey'),
                'thumbnail' => 'images/products/community-pro-2.png',
                'short_description' => 'Natural and pure honey.',
                'description' => 'Unprocessed, raw honey collected from organic sources.',
                'buying_price' => 180.00,
                'selling_price' => 220.00,
                'discount_type' => 'flat',
                'discount_amount' => 15.00,
                'quantity' => 40,
                'unit' => '500 gm',
                'category_id' => 6,
                'brand_id' => 7,
                'seller_id' => 1,
                'sku' => 'GRY-HON-006',
                'barcode' => '6789012345678',
                'is_community' => 1,
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 40,
                'stock_out' => 8,
                'shipping_cost' => 8.00,
                'tax' => 6.00,
                'views' => 1000,
            ],

            // halloween

            [
                'name' => 'Spooky Pumpkin Stickers',
                'slug' => Str::slug('Spooky Pumpkin Stickers'),
                'thumbnail' => 'images/products/halloween-product-3.png',
                'short_description' => 'Set of spooky pumpkin stickers for Halloween decoration.',
                'description' => 'A collection of high-quality, waterproof pumpkin stickers for decorating your home, laptop, or Halloween party.',
                'buying_price' => 50.00,
                'selling_price' => 80.00,
                'discount_type' => 'percentage',
                'discount_amount' => 10.00,
                'quantity' => 100,
                'unit' => '1 Pack',
                'category_id' => 3,
                'brand_id' => 1,
                'seller_id' => 1,
                'sku' => 'HAL-STK-001',
                'barcode' => '1234567890123',
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 100,
                'stock_out' => 20,
                'shipping_cost' => 5.00,
                'tax' => 5.00,
                'views' => 500,
            ],
            [
                'name' => 'Scary Witch Costume',
                'slug' => Str::slug('Scary Witch Costume'),
                'thumbnail' => 'images/products/halloween-product-1.png',
                'short_description' => 'Classic Halloween witch costume for kids and adults.',
                'description' => 'A high-quality, comfortable witch costume with a spooky design, perfect for Halloween parties.',
                'buying_price' => 300.00,
                'selling_price' => 450.00,
                'discount_type' => 'flat',
                'discount_amount' => 30.00,
                'quantity' => 30,
                'unit' => '1 Set',
                'category_id' => 3,
                'brand_id' => 1,
                'seller_id' => 1,
                'sku' => 'HAL-COS-002',
                'barcode' => '2345678901234',
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 30,
                'stock_out' => 5,
                'shipping_cost' => 15.00,
                'tax' => 10.00,
                'views' => 750,
            ],
            [
                'name' => 'Pumpkin Candy Bucket',
                'slug' => Str::slug('Pumpkin Candy Bucket'),
                'thumbnail' => 'images/products/halloween-product-4.png',
                'short_description' => 'A Halloween-themed pumpkin bucket filled with assorted candies.',
                'description' => 'A fun and spooky candy bucket shaped like a pumpkin, packed with a variety of Halloween treats.',
                'buying_price' => 120.00,
                'selling_price' => 170.00,
                'discount_type' => 'percentage',
                'discount_amount' => 15.00,
                'quantity' => 50,
                'unit' => '1 Bucket',
                'category_id' => 3,
                'brand_id' => 1,
                'seller_id' => 1,
                'sku' => 'HAL-FD-003',
                'barcode' => '3456789012345',
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 50,
                'stock_out' => 10,
                'shipping_cost' => 7.00,
                'tax' => 8.00,
                'views' => 600,
            ],
            [
                'name' => 'Glow-in-the-Dark Ghost Stickers',
                'slug' => Str::slug('Glow-in-the-Dark Ghost Stickers'),
                'thumbnail' => 'images/products/halloween-product-5.png',
                'short_description' => 'Halloween ghost stickers that glow in the dark.',
                'description' => 'A spooky collection of glow-in-the-dark ghost stickers, perfect for Halloween decorations and crafts.',
                'buying_price' => 60.00,
                'selling_price' => 90.00,
                'discount_type' => 'flat',
                'discount_amount' => 10.00,
                'quantity' => 80,
                'unit' => '1 Pack',
                'category_id' => 3,
                'brand_id' => 1,
                'seller_id' => 1,
                'sku' => 'HAL-STK-004',
                'barcode' => '4567890123456',
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 80,
                'stock_out' => 15,
                'shipping_cost' => 5.00,
                'tax' => 5.00,
                'views' => 450,
            ],
            [
                'name' => 'Vampire Cape Costume',
                'slug' => Str::slug('Vampire Cape Costume'),
                'thumbnail' => 'images/products/halloween-product-2.png',
                'short_description' => 'A spooky vampire cape for Halloween.',
                'description' => 'A classic vampire cape made from high-quality fabric, perfect for Halloween parties and trick-or-treating.',
                'buying_price' => 250.00,
                'selling_price' => 350.00,
                'discount_type' => 'percentage',
                'discount_amount' => 20.00,
                'quantity' => 25,
                'unit' => '1 Set',
                'category_id' => 3,
                'brand_id' => 1,
                'seller_id' => 1,
                'sku' => 'HAL-COS-005',
                'barcode' => '5678901234567',
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 25,
                'stock_out' => 3,
                'shipping_cost' => 12.00,
                'tax' => 10.00,
                'views' => 700,
            ],
            [
                'name' => 'Halloween Spider Cookies',
                'slug' => Str::slug('Halloween Spider Cookies'),
                'thumbnail' => 'images/products/halloween-product-4.png',
                'short_description' => 'Delicious chocolate cookies decorated like spooky spiders.',
                'description' => 'A tasty treat for Halloween parties, these chocolate cookies are shaped and decorated like creepy spiders.',
                'buying_price' => 100.00,
                'selling_price' => 150.00,
                'discount_type' => 'flat',
                'discount_amount' => 10.00,
                'quantity' => 60,
                'unit' => '1 Box',
                'category_id' => 3,
                'brand_id' => 1,
                'seller_id' => 1,
                'sku' => 'HAL-FD-006',
                'barcode' => '6789012345678',
                'status' => 1,
                'stock_status' => 'in_stock',
                'stock_in' => 60,
                'stock_out' => 12,
                'shipping_cost' => 6.00,
                'tax' => 7.00,
                'views' => 550,
            ],
        ];

        foreach ($products as $product) {
            Product::insert([
                'name' => $product['name'],
                'slug' => $product['slug'],
                'thumbnail' => $product['thumbnail'],
                'short_description' => $product['short_description'],
                'description' => $product['description'],
                'buying_price' => $product['buying_price'],
                'selling_price' => $product['selling_price'],
                'discount_type' => $product['discount_type'],
                'discount_amount' => $product['discount_amount'],
                'quantity' => $product['quantity'],
                'unit' => $product['unit'] ?? null,
                'category_id' => $product['category_id'],
                'brand_id' => $product['brand_id'] ?? null,
                'seller_id' => $product['seller_id'],
                'sku' => $product['sku'],
                'barcode' => $product['barcode'],
                'is_trending' => $product['is_trending'] ?? 0,
                'is_community' => $product['is_community'] ?? 0,
                'is_interest' => $product['is_interest'] ?? 0,
                'is_lightdeal' => $product['is_lightdeal'] ?? 0,
                'lightdeal_expired_at' => $product['lightdeal_expired_at'] ?? null,
                'best_selling' => $product['best_selling'] ?? 0,
                'is_featured' => $product['is_featured'] ?? 0,
                'status' => $product['status'],
                'stock_status' => $product['stock_status'],
                'stock_in' => $product['stock_in'],
                'stock_out' => $product['stock_out'],
                'shipping_cost' => $product['shipping_cost'],
                'tax' => $product['tax'],
                'views' => $product['views'],
            ]);
        }
    }
}
